
package com.cisco.axlapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2021-08-05T18:34:26.666-05:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "axlError", targetNamespace = "http://www.cisco.com/AXL/API/11.5")
public class AXLError extends Exception {
    
    private com.cisco.axl.api._11.AXLError axlError;

    public AXLError() {
        super();
    }
    
    public AXLError(String message) {
        super(message);
    }
    
    public AXLError(String message, Throwable cause) {
        super(message, cause);
    }

    public AXLError(String message, com.cisco.axl.api._11.AXLError axlError) {
        super(message);
        this.axlError = axlError;
    }

    public AXLError(String message, com.cisco.axl.api._11.AXLError axlError, Throwable cause) {
        super(message, cause);
        this.axlError = axlError;
    }

    public com.cisco.axl.api._11.AXLError getFaultInfo() {
        return this.axlError;
    }
}
