
package com.github.casuallyblue.cucm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * Generated source version: 3.4.4
 */

@WebFault(name = "axlError", targetNamespace = "http://www.cisco.com/AXL/API/11.5")
public class AXLError_Exception extends Exception {

    private com.github.casuallyblue.cucm.AXLError faultInfo;

    public AXLError_Exception() {
        super();
    }

    public AXLError_Exception(String message) {
        super(message);
    }

    public AXLError_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AXLError_Exception(String message, com.github.casuallyblue.cucm.AXLError axlError) {
        super(message);
        this.faultInfo = axlError;
    }

    public AXLError_Exception(String message, com.github.casuallyblue.cucm.AXLError axlError, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = axlError;
    }

    public com.github.casuallyblue.cucm.AXLError getFaultInfo() {
        return this.faultInfo;
    }
}
