
package com.github.casuallyblue.cucm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XCommonMembersExtension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XCommonMembersExtension"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XCommonMembersExtension")
@XmlSeeAlso({
    com.github.casuallyblue.cucm.UpdateTimeScheduleReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateTimeScheduleReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateTimeScheduleReq.Members.class,
    com.github.casuallyblue.cucm.UpdateCallerFilterListReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateCallerFilterListReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateCallerFilterListReq.Members.class,
    com.github.casuallyblue.cucm.UpdateCssReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateCssReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateCssReq.Members.class,
    com.github.casuallyblue.cucm.UpdateMediaResourceGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateMediaResourceGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateMediaResourceGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateMediaResourceListReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateMediaResourceListReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateMediaResourceListReq.Members.class,
    com.github.casuallyblue.cucm.UpdateRouteGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateRouteGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateRouteGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateResourcePriorityNamespaceListReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateResourcePriorityNamespaceListReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateResourcePriorityNamespaceListReq.Members.class,
    com.github.casuallyblue.cucm.UpdateDeviceMobilityReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateDeviceMobilityReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateDeviceMobilityReq.Members.class,
    com.github.casuallyblue.cucm.UpdateHuntListReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateHuntListReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateHuntListReq.Members.class,
    com.github.casuallyblue.cucm.UpdateLineGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateLineGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateLineGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateRouteFilterReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateRouteFilterReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateRouteFilterReq.Members.class,
    com.github.casuallyblue.cucm.UpdateCallManagerGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateCallManagerGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateCallManagerGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateUserGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateUserGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateUserGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateUserGroupReq.RemoveUserRoles.class,
    com.github.casuallyblue.cucm.UpdateUserGroupReq.AddUserRoles.class,
    com.github.casuallyblue.cucm.UpdateUserGroupReq.UserRoles.class,
    com.github.casuallyblue.cucm.UpdateMobileVoiceAccessReq.RemoveLocales.class,
    com.github.casuallyblue.cucm.UpdateMobileVoiceAccessReq.AddLocales.class,
    com.github.casuallyblue.cucm.UpdateMobileVoiceAccessReq.Locales.class,
    com.github.casuallyblue.cucm.UpdateRouteListReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateRouteListReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateRouteListReq.Members.class,
    com.github.casuallyblue.cucm.UpdateUserReq.RemoveExtensionsInfo.class,
    com.github.casuallyblue.cucm.UpdateUserReq.AddExtensionsInfo.class,
    com.github.casuallyblue.cucm.UpdateUserReq.ExtensionsInfo.class,
    com.github.casuallyblue.cucm.UpdateDateTimeGroupReq.RemovePhoneNtpReferences.class,
    com.github.casuallyblue.cucm.UpdateDateTimeGroupReq.AddPhoneNtpReferences.class,
    com.github.casuallyblue.cucm.UpdateDateTimeGroupReq.PhoneNtpReferences.class,
    com.github.casuallyblue.cucm.UpdateApplicationServerReq.RemoveAppUsers.class,
    com.github.casuallyblue.cucm.UpdateApplicationServerReq.AddAppUsers.class,
    com.github.casuallyblue.cucm.UpdateApplicationServerReq.AppUsers.class,
    com.github.casuallyblue.cucm.UpdateApplicationServerReq.RemoveEndUsers.class,
    com.github.casuallyblue.cucm.UpdateApplicationServerReq.AddEndUsers.class,
    com.github.casuallyblue.cucm.UpdateApplicationServerReq.EndUsers.class,
    com.github.casuallyblue.cucm.UpdateIpPhoneServicesReq.RemoveParameters.class,
    com.github.casuallyblue.cucm.UpdateIpPhoneServicesReq.AddParameters.class,
    com.github.casuallyblue.cucm.UpdateIpPhoneServicesReq.Parameters.class,
    com.github.casuallyblue.cucm.UpdateSipDialRulesReq.RemovePatterns.class,
    com.github.casuallyblue.cucm.UpdateSipDialRulesReq.AddPatterns.class,
    com.github.casuallyblue.cucm.UpdateSipDialRulesReq.Patterns.class,
    com.github.casuallyblue.cucm.UpdateSipDialRulesReq.RemovePlars.class,
    com.github.casuallyblue.cucm.UpdateSipDialRulesReq.AddPlars.class,
    com.github.casuallyblue.cucm.UpdateSipDialRulesReq.Plars.class,
    com.github.casuallyblue.cucm.UpdateH323TrunkReq.RemoveDestinations.class,
    com.github.casuallyblue.cucm.UpdateH323TrunkReq.AddDestinations.class,
    com.github.casuallyblue.cucm.UpdateH323TrunkReq.Destinations.class,
    com.github.casuallyblue.cucm.UpdateRemoteDestinationReq.RemoveRingSchedule.class,
    com.github.casuallyblue.cucm.UpdateRemoteDestinationReq.AddRingSchedule.class,
    com.github.casuallyblue.cucm.UpdateRemoteDestinationReq.RingSchedule.class,
    com.github.casuallyblue.cucm.UpdateCallPickupGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateCallPickupGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateCallPickupGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateGeoLocationPolicyReq.RemoveRelatedPolicies.class,
    com.github.casuallyblue.cucm.UpdateGeoLocationPolicyReq.AddRelatedPolicies.class,
    com.github.casuallyblue.cucm.UpdateGeoLocationPolicyReq.RelatedPolicies.class,
    com.github.casuallyblue.cucm.UpdateSipTrunkReq.RemoveDestinations.class,
    com.github.casuallyblue.cucm.UpdateSipTrunkReq.AddDestinations.class,
    com.github.casuallyblue.cucm.UpdateSipTrunkReq.Destinations.class,
    com.github.casuallyblue.cucm.UpdateSafForwarderReq.RemoveAssociatedCucms.class,
    com.github.casuallyblue.cucm.UpdateSafForwarderReq.AddAssociatedCucms.class,
    com.github.casuallyblue.cucm.UpdateSafForwarderReq.AssociatedCucms.class,
    com.github.casuallyblue.cucm.UpdateCcdRequestingServiceReq.RemoveAssociatedTrunks.class,
    com.github.casuallyblue.cucm.UpdateCcdRequestingServiceReq.AddAssociatedTrunks.class,
    com.github.casuallyblue.cucm.UpdateCcdRequestingServiceReq.AssociatedTrunks.class,
    com.github.casuallyblue.cucm.UpdateLdapDirectoryReq.RemoveAccessControlGroupInfo.class,
    com.github.casuallyblue.cucm.UpdateLdapDirectoryReq.AddAccessControlGroupInfo.class,
    com.github.casuallyblue.cucm.UpdateLdapDirectoryReq.AccessControlGroupInfo.class,
    com.github.casuallyblue.cucm.UpdateImeClientReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateImeClientReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateImeClientReq.Members.class,
    com.github.casuallyblue.cucm.UpdateImeClientReq.RemoveCcmExternalIpMaps.class,
    com.github.casuallyblue.cucm.UpdateImeClientReq.AddCcmExternalIpMaps.class,
    com.github.casuallyblue.cucm.UpdateImeClientReq.CcmExternalIpMaps.class,
    com.github.casuallyblue.cucm.UpdateLbmHubGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateLbmHubGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateLbmHubGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateWlanProfileGroupReq.RemoveMembers.class,
    com.github.casuallyblue.cucm.UpdateWlanProfileGroupReq.AddMembers.class,
    com.github.casuallyblue.cucm.UpdateWlanProfileGroupReq.Members.class,
    com.github.casuallyblue.cucm.UpdateElinGroupReq.RemoveElinNumbers.class,
    com.github.casuallyblue.cucm.UpdateElinGroupReq.AddElinNumbers.class,
    com.github.casuallyblue.cucm.UpdateElinGroupReq.ElinNumbers.class,
    com.github.casuallyblue.cucm.UpdateSelfProvisioningReq.RemoveLanguages.class,
    com.github.casuallyblue.cucm.UpdateSelfProvisioningReq.AddLanguages.class,
    com.github.casuallyblue.cucm.UpdateSelfProvisioningReq.Languages.class,
    com.github.casuallyblue.cucm.XTimeSchedule.Members.class,
    com.github.casuallyblue.cucm.XCallerFilterList.Members.class,
    com.github.casuallyblue.cucm.XCss.Members.class,
    com.github.casuallyblue.cucm.XMediaResourceGroup.Members.class,
    com.github.casuallyblue.cucm.XMediaResourceList.Members.class,
    com.github.casuallyblue.cucm.XRouteGroup.Members.class,
    com.github.casuallyblue.cucm.XResourcePriorityNamespaceList.Members.class,
    com.github.casuallyblue.cucm.XDeviceMobility.Members.class,
    com.github.casuallyblue.cucm.XHuntList.Members.class,
    com.github.casuallyblue.cucm.XLineGroup.Members.class,
    com.github.casuallyblue.cucm.XRouteFilter.Members.class,
    com.github.casuallyblue.cucm.XCallManagerGroup.Members.class,
    com.github.casuallyblue.cucm.XUserGroup.Members.class,
    com.github.casuallyblue.cucm.XUserGroup.UserRoles.class,
    com.github.casuallyblue.cucm.XDdi.Members.class,
    com.github.casuallyblue.cucm.XMobileVoiceAccess.Locales.class,
    com.github.casuallyblue.cucm.XRouteList.Members.class,
    com.github.casuallyblue.cucm.XUser.ExtensionsInfo.class,
    com.github.casuallyblue.cucm.XDateTimeGroup.PhoneNtpReferences.class,
    com.github.casuallyblue.cucm.XApplicationServer.AppUsers.class,
    com.github.casuallyblue.cucm.XApplicationServer.EndUsers.class,
    com.github.casuallyblue.cucm.XIpPhoneServices.Parameters.class,
    com.github.casuallyblue.cucm.XSipDialRules.Patterns.class,
    com.github.casuallyblue.cucm.XSipDialRules.Plars.class,
    com.github.casuallyblue.cucm.XH323Trunk.Destinations.class,
    com.github.casuallyblue.cucm.XRemoteDestination.RingSchedule.class,
    com.github.casuallyblue.cucm.XCallPickupGroup.Members.class,
    com.github.casuallyblue.cucm.XGeoLocationPolicy.RelatedPolicies.class,
    com.github.casuallyblue.cucm.XSipTrunk.Destinations.class,
    com.github.casuallyblue.cucm.XSafForwarder.AssociatedCucms.class,
    com.github.casuallyblue.cucm.XCcdRequestingService.AssociatedTrunks.class,
    com.github.casuallyblue.cucm.XLdapDirectory.AccessControlGroupInfo.class,
    com.github.casuallyblue.cucm.XImeClient.Members.class,
    com.github.casuallyblue.cucm.XImeClient.CcmExternalIpMaps.class,
    com.github.casuallyblue.cucm.XLbmHubGroup.Members.class,
    com.github.casuallyblue.cucm.XSdpTransparencyProfile.AttributeSet.class,
    com.github.casuallyblue.cucm.XWlanProfileGroup.Members.class,
    com.github.casuallyblue.cucm.XElinGroup.ElinNumbers.class,
    com.github.casuallyblue.cucm.LLdapDirectory.AccessControlGroupInfo.class,
    com.github.casuallyblue.cucm.LElinGroup.ElinNumbers.class
})
public class XCommonMembersExtension {


}
